
STATUS_RESPONCE = 200
CONTENT = "application/json"
ACTION = "presense"
UNIX_TIME = 1
USER = 'user'
ACCOUNT = "account_name"
PASSWORD = "password"
MESSAGE = 'message'
MESSAGE_TEXT = 'mess_text'
TIME = 'time'
ACCOUNT_NAME = 'account_name'
GET_CONTACTS = 'get_contacts'
LIST_INFO = 'data_list'
REMOVE_CONTACT = 'remove'
ADD_CONTACT = 'add'
USERS_REQUEST = 'get_users'
SENDER = 'from'
DESTINATION = 'to'
EXIT = 'exit'
PRESENCE = 'presence'
RESPONSE = 'response'
ERROR = 'error'
RESPONSE_200 = {RESPONSE: 200}
RESPONSE_202 = {RESPONSE: 202, LIST_INFO: None}
RESPONSE_400 = {RESPONSE: 400}
DEFAULT_PORT = 7777
DEFAULT_IP_ADDRESS = '127.0.0.1'
MAX_CONNECTIONS = 5
MAX_PACKAGE_LENGTH = 1024
ENCODING = 'utf-8'